source ; https://www.youtube.com/watch?v=pkVwUVEHmfI

In [2]:
import numpy as np

In [10]:
# not application
A = np.random.rand(3,5)
B = np.random.rand(5,2)
M = np.empty((3,2))

# Free Indices ; i,j
for i in range(3):
    for j in range(2):
        # Summation Index ; k
        total = 0
        for k in range(5):
            # Summation index ; k
            total += A[i,k]*B[k,j]
            
        M[i,j] = total

In [7]:
# Einsum application
M = np.einsum('ik,kj->ij', A, B)

In [8]:
M

array([[2.37649447, 1.80557001],
       [2.54415001, 2.40298472],
       [1.4952114 , 1.39873301]])

# RULES;

1. Repeating letters in different inputs means those values will be multiplied and 
those products will be the output.


2. Omitting a letter menas that axis will be summed.


3. We can return the unsummed axes in any order.

In [19]:
# Rule 1
M = np.einsum('ik,kj->ij', A,B)
print(type(M))
M

<class 'numpy.ndarray'>


array([[1.08955729, 1.29767946],
       [1.90735073, 2.33647196],
       [0.85765927, 1.112434  ]])

In [18]:
# Rule 2
x = np.ones(3)
sum_x = np.einsum('i->', x)
print(type(sum_x))
sum_x

<class 'numpy.float64'>


3.0

In [20]:
# Rule 3
x = np.ones((5, 4, 3))
np.einsum('ijk->kji', x)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [21]:
import torch

torch.einsum

<function torch.functional.einsum(equation, *operands)>

In [22]:
x = torch.rand((2, 3))

In [25]:
# Permutation of Tensors
torch.einsum('ij->ji', x)

tensor([[0.2443, 0.2797],
        [0.5276, 0.6815],
        [0.7611, 0.4686]])

In [26]:
# Summation
torch.einsum('ij->', x)

tensor(2.9628)

In [27]:
# Column Sum
torch.einsum('ij->j', x)

tensor([0.5240, 1.2091, 1.2297])

In [28]:
# Row sum
torch.einsum('ij->i', x)

tensor([1.5330, 1.4298])

In [31]:
# Matrix-Vector Multiplication
v = torch.rand((1,3))
torch.einsum('ij, kj->ik', x, v)

tensor([[0.5223],
        [0.3910]])

In [32]:
v

tensor([[0.3234, 0.0774, 0.5288]])

In [33]:
# Matrix-Matrix Multiplication
torch.einsum('ij,kj->ik',x,x) # 2 x 2 : 2x3 X 3x2

tensor([[0.9172, 0.7845],
        [0.7845, 0.7623]])

In [34]:
# Dot product first row with first row of matrix
torch.einsum('i,i->', x[0], x[0])

tensor(0.9172)

In [35]:
# Dot product with matrix
torch.einsum('ij,ij->', x, x)

tensor(1.6795)

In [36]:
# Hadamard Product (element - wise multiplication)
torch.einsum('ij,ij->ij', x, x)

tensor([[0.0597, 0.2783, 0.5792],
        [0.0782, 0.4644, 0.2196]])

In [41]:
# Outer Product
a = torch.rand((3))
b = torch.rand((5))
torch.einsum('i,j->ij', a, b)


tensor([[0.0026, 0.0046, 0.0010, 0.0035, 0.0033],
        [0.0493, 0.0856, 0.0193, 0.0658, 0.0610],
        [0.0561, 0.0975, 0.0219, 0.0749, 0.0695]])

In [44]:
print(a)
print(b)

tensor([0.0050, 0.0931, 0.1061])
tensor([0.5289, 0.9195, 0.2068, 0.7067, 0.6552])


In [47]:
# Batch Matrix Multiplication
# Need to dimension matching
a = torch.rand((3, 2, 5))
b = torch.rand((3, 5, 3))
torch.einsum('ijk,ikl->ijl', a, b)

tensor([[[1.8732, 2.6603, 2.4451],
         [1.3000, 2.0495, 1.9470]],

        [[0.6674, 1.3453, 1.2307],
         [0.9407, 1.7426, 1.6988]],

        [[1.1765, 0.9820, 0.9141],
         [1.1339, 1.4831, 1.3191]]])

In [50]:
# Matrix Diagnoal
x = torch.rand((3,3))
print(x)
torch.einsum('ii->i', x)

tensor([[0.3694, 0.4146, 0.8159],
        [0.0633, 0.0363, 0.0241],
        [0.8325, 0.1307, 0.8527]])


tensor([0.3694, 0.0363, 0.8527])

In [53]:
# Matrix Trace -> '대각합'
torch.einsum('ii->', x)

tensor(1.2584)